import React from 'react';
import { View } from 'react-native';
export const Animated = { View: (p: any) => <View {...p} /> };
export const useSharedValue = (v: any) => ({ value: v });
export const useAnimatedStyle = () => ({});
export const withSpring = (v: any) => v;
export const withSequence = (...a: any[]) => a[a.length - 1];
export const useDerivedValue = (fn: () => any) => ({ value: fn() });
export const useAnimatedProps = () => ({});
export const withTiming = (v: any) => v;
export const withRepeat = (v: any) => v;
export const withDelay = (v: any) => v;
export const interpolate = (v: any) => v;
export const Extrapolation = { CLAMP: 'clamp', EXTEND: 'extend', IDENTITY: 'identity' };
export const FadeIn = { duration: () => ({}) };
export const FadeOut = { duration: () => ({}) };
export const runOnJS = (fn: any) => fn;
export const runOnUI = (fn: any) => fn;
export const measure = () => ({});
export const scrollTo = () => {};
export const configureReanimatedLogger = () => {};
export const ReanimatedLogLevel = { warn: 'warn', error: 'error' };
export default Animated;
